version: '3.8'
services:
database:
image: mysql:8.0
container_name: db
environment:
MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
MYSQL_DATABASE: transaction
MYSQL_USER: ${DB_USER}
MYSQL_PASSWORD: ${DB_PASSWORD}
ports:
- "3306:3306"
networks:
- transaction-network
kafka:
image: wurstmeister/kafka:2.13-2.7.0
ports:
- "9092:9092"
environment:
KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
zookeeper:
image: wurstmeister/zookeeper:3.4.6
ports:
- "2181:2181"
app:
build: .
ports:
- "8080:8080"
environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/transaction
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      APP_SECRET: ${APP_SECRET}
      
depends_on:
- database

networks:
- transaction-network
